site_name: Figma for Beginners
site_description: A beginner's guide to Figma
site_url: https://ramandeepkaurkainth.github.io/mkdocs-Comm2216/
copyright: © 2025 Ramandeep Kaur and Kiana Karimi

# Navigation (unchanged, just corrected indentation)
nav:
  - Home: index.md
  - Creating and Using Components: components.md
  - Creating a Design Layout: design-layout.md
  - Prototyping a Button Interaction: prototyping.md
  - Glossary: glossary.md
  - Troubleshooting Guide: troubleshooting.md

theme:
  name: material
  font:
    text: Merriweather Sans
    code: Red Hat Display
  logo: assets/62c6bc3deee9410fe137d920.png
  favicon: assets/85f69649-5387-44c2-ba45-81ae13812e36-cover.png
  features:
    - navigation.footer
  palette:
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: green
      accent: deep purple
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: blue
      accent: grey

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details